version: '2'

services:
   db:
        image: mysql
        container_name: ${MYSQL_HOST}
        restart: always
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_HOST=%
   shortner-web:
        depends_on:
            - db
        volumes:
            - ./shortner-web:/usr/src/api
        links:
            - db:${MYSQL_HOST}
        build:
            context: shortner-web 
        environment:
            - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@${MYSQL_HOST}:3306/${MYSQL_DATABASE}
        ports:
            - 8080:8080
